### ISSUE TITLE
MaskedArrayFutureWarning Numpy 1.11 - does this require some cdms tweaks?

### ISSUE THREAD

**Issue by durack1** [CDAT/cdms#122]
It seems the following error is being triggered very often:
```
make_masks.py:247: MaskedArrayFutureWarning: setting an item on a masked array which has a shared
mask will not copy the mask and also change the original mask array in the future.
Check the NumPy 1.11 release notes for more information.
  basinmask3[yInd,xInd] = 2 ; # Correct to Pacific
```

**Comment by doutriaux1** [comment]
it's a numpy thing.

**Comment by durack1** [comment]
@doutriaux1 I don't agree, the `transientVariable` masks are being used within software, these are inherited from numpy, and so any changes upstream will affect the functionality

**Comment by doutriaux1** [comment]
ok I thought your array was a numpy.      @dnadeau4  can you takealook?

**Comment by jypeter** [comment]
I agree with @durack1 that we want to be sure that the warning above will not lead to unexpected side effects. cdms handling masks correctly behind the scene without the user having to think about it is one of cdms assets.

Beginning users are often quite clueless about masks and at best know about NaN and you have to fight with them to use clean masks rather than rely on NaN (I think NaN is a matlab thing). Teaching newcomers to use masks correctly is on the same level as teaching them that they have to use weights for spatial averages (i.e. use cdutil.averager) rather than just performing a regular average
